"""
Communication agent — drafts emails, sends notifications, sets calendar reminders.
Extended to read roadmap_structured from GraphState for the A2A email-roadmap demo.
"""
from datetime import datetime as dt
from langchain_groq import ChatGroq
from langchain_ollama import ChatOllama
from app.config import GROQ_API_KEY, LOCAL_FALLBACK_MODEL
from app.state import GraphState
from app.tools.mock_data import get_student, load_communications, save_communications
from app.tools.google_calendar import create_event_with_reminder
from app.tools.mock_data import load_placements

llm = ChatGroq(model="llama-3.3-70b-versatile", api_key=GROQ_API_KEY, temperature=0)


def _invoke_llm(prompt: str) -> str:
    try:
        return llm.invoke(prompt).content
    except Exception as e:
        if "429" in str(e) or "rate limit" in str(e).lower():
            return ChatOllama(model=LOCAL_FALLBACK_MODEL, temperature=0).invoke(prompt).content
        raise


def draft_email(student_name: str, purpose: str) -> str:
    """LLM drafts the actual email text — legitimate LLM work (unlike eligibility/attendance)."""
    prompt = f"""Draft a short, polite, professional email from a student named
{student_name} to college administration. Purpose: {purpose}
Keep it under 120 words. Include a subject line."""
    return _invoke_llm(prompt)


def send_notification(student_id: str, message: str) -> dict:
    data = load_communications()
    entry = {
        "student_id": student_id,
        "message": message,
        "timestamp": dt.now().isoformat(),
    }
    data["notifications"].append(entry)
    save_communications(data)
    return entry


def add_calendar_reminder(student_id: str, event_name: str, remind_before: str) -> dict:
    data = load_communications()
    entry = {
        "student_id": student_id,
        "event": event_name,
        "remind_before": remind_before,
        "created_at": dt.now().isoformat(),
    }
    data["calendar"].append(entry)
    save_communications(data)
    return entry


def save_email(student_id: str, content: str) -> dict:
    data = load_communications()
    entry = {
        "student_id": student_id,
        "content": content,
        "timestamp": dt.now().isoformat(),
    }
    data["emails"].append(entry)
    save_communications(data)
    return entry


def _send_roadmap_email(student: dict, roadmap_content: str, topic: str) -> str:
    """
    Send the roadmap generated by roadmap_node to the student via SMTP.
    This is the A2A demo: communication_node reads roadmap_structured
    (written by roadmap_node) directly from GraphState.
    """
    import os, smtplib
    from email.mime.multipart import MIMEMultipart
    from email.mime.text import MIMEText

    student_email = student.get("email", "")
    if not student_email:
        return "Could not send email: student email address not found in database."

    smtp_user = os.getenv("SMTP_USER", "")
    smtp_pass = os.getenv("SMTP_PASSWORD", "")
    smtp_host = os.getenv("SMTP_HOST", "smtp.zoho.in")
    smtp_port = int(os.getenv("SMTP_PORT", "465"))
    from_email = os.getenv("SMTP_FROM_EMAIL", smtp_user)

    if not smtp_user or not smtp_pass:
        return "SMTP not configured — roadmap saved but could not be emailed."

    # Build a clean HTML version of the roadmap
    html_body = f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"/></head>
<body style="font-family:'Segoe UI',Arial,sans-serif;background:#0f172a;color:#e2e8f0;padding:40px;">
  <div style="max-width:700px;margin:0 auto;background:#1e293b;border-radius:16px;padding:36px;">
    <div style="background:linear-gradient(135deg,#6366f1,#0ea5e9);padding:24px 32px;
                border-radius:12px;margin-bottom:32px;text-align:center;">
      <h1 style="margin:0;color:#fff;font-size:22px;">🗺️ Your Learning Roadmap</h1>
      <p style="margin:8px 0 0;color:rgba(255,255,255,0.8);font-size:14px;">
        Topic: {topic} · Generated by Smart Campus AI
      </p>
    </div>
    <div style="white-space:pre-wrap;font-size:14px;line-height:1.8;color:#cbd5e1;">
{roadmap_content}
    </div>
    <hr style="border-color:#334155;margin:32px 0"/>
    <p style="font-size:12px;color:#475569;text-align:center;">
      Smart Campus ERP · Generated with LangGraph + Groq
    </p>
  </div>
</body>
</html>"""

    try:
        server = smtplib.SMTP_SSL(smtp_host, smtp_port)
        server.login(smtp_user, smtp_pass)

        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"📚 Your {topic} Learning Roadmap — Smart Campus"
        msg["From"] = f"Smart Campus <{from_email}>"
        msg["To"] = student_email
        msg.attach(MIMEText(html_body, "html"))
        server.sendmail(from_email, student_email, msg.as_string())
        server.quit()
        return f"✅ Roadmap emailed to {student_email}."
    except Exception as e:
        return f"Email failed ({e}). Roadmap is saved to your profile."


def communication_node(state: GraphState) -> GraphState:
    idx = state["current_step_index"]
    task = state["plan"][idx]["task"]
    student = get_student(state["student_id"])

    # Fall back to DB if mock data doesn't have this student
    if not student:
        from app.database import get_student_record
        student = get_student_record(state["student_id"]) or {"name": state["student_id"]}

    student_name = student.get("name", state["student_id"])
    task_lower = task.lower()
    outputs = []

    # ── A2A: Email roadmap if roadmap_structured is present ───────────────────
    if "email" in task_lower and state["agent_outputs"].get("roadmap_structured"):
        roadmap_data = state["agent_outputs"]["roadmap_structured"]
        result = _send_roadmap_email(
            student=student,
            roadmap_content=roadmap_data.get("content", ""),
            topic=roadmap_data.get("topic", "Learning Roadmap"),
        )
        outputs.append(result)

    elif "email" in task_lower or "draft" in task_lower:
        email_content = draft_email(student_name, task)
        save_email(state["student_id"], email_content)
        outputs.append(f"Email drafted and saved:\n{email_content}")

    if "calendar" in task_lower or "remind" in task_lower:
        result_text = handle_calendar_and_reminder(state["student_id"], task)
        outputs.append(result_text)

    if "notif" in task_lower:
        send_notification(state["student_id"], task)
        outputs.append(f"Notification sent: {task}")

    if not outputs:
        outputs.append(f"No matching communication action found for: {task}")

    state["agent_outputs"].setdefault("communication", []).append(" | ".join(outputs))
    state["plan"][idx]["status"] = "done"
    state["current_step_index"] += 1
    return state


def handle_calendar_and_reminder(student_id: str, task: str) -> str:
    data = load_placements()
    matched = next((e for e in data["events"] if e["company"].lower() in task.lower()), None)

    if not matched:
        return f"Could not find a matching event for: {task}"
    comms = load_communications()
    already_done = any(
        c.get("student_id") == student_id and c.get("event") == matched["name"]
        for c in comms.get("calendar", [])
    )
    if already_done:
        return f"'{matched['name']}' is already on your calendar with a reminder set."

    event_date = matched["date"]
    event_time = matched["time"]
    start_dt = dt.strptime(f"{event_date} {event_time}", "%Y-%m-%d %I:%M %p")

    result = create_event_with_reminder(
        summary=matched["name"],
        start_dt=start_dt,
        reminder_minutes_before=60,
    )

    if result["success"]:
        return f"Added '{matched['name']}' to your Google Calendar with a 1-hour reminder: {result['link']}"
    else:
        add_calendar_reminder(student_id, matched["name"], "1 hour before")
        return f"Google Calendar unavailable, saved '{matched['name']}' to local reminder instead."